apiVersion: v1
kind: Secret
metadata:
  name: git-creds
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
type: Opaque
stringData:
  username: git
  password: {{ required "gitCreds.password is required" .Values.gitCreds.password | quote }}
