apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.repoCredentials.secretName | quote }}
  namespace: {{ .Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-ssm
    kind: ClusterSecretStore
  target:
    name: {{ .Values.repoCredentials.secretName | quote }}
    creationPolicy: Owner
    template:
      type: Opaque
      metadata:
        labels:
          argocd.argoproj.io/secret-type: repository
      data:
        type: git
        url: {{ required "repoCredentials.repoURL is required" .Values.repoCredentials.repoURL | quote }}
        username: {{ required "repoCredentials.username is required" .Values.repoCredentials.username | quote }}
        password: {{ printf "{{ .password }}" | quote }}
  data:
    - secretKey: password
      remoteRef:
        key: {{ required "repoCredentials.tokenSsmParameter is required" .Values.repoCredentials.tokenSsmParameter | quote }}
