apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.rootApplication.name | quote }}
  namespace: {{ .Release.Namespace }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ required "rootApplication.repoURL is required" .Values.rootApplication.repoURL | quote }}
    targetRevision: {{ .Values.rootApplication.targetRevision | quote }}
    path: {{ .Values.rootApplication.path | quote }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Release.Namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
