apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "express-app.fullname" . }}
  labels:
    {{- include "express-app.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "express-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "express-app.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "express-app.name" . }}
          image: "{{ required "image.repository is required" .Values.image.repository }}:{{ required "image.tag is required" .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          env:
            - name: PORT
              value: {{ .Values.containerPort | quote }}
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
