storageClass:
  enabled: true
  name: observability-gp3
  isDefault: true
  provisioner: ebs.csi.aws.com
  reclaimPolicy: Delete
  volumeBindingMode: WaitForFirstConsumer
  allowVolumeExpansion: true
  parameters:
    type: gp3
    encrypted: "true"

kube-prometheus-stack:
  alertmanager:
    enabled: false

  prometheus:
    enabled: true

  grafana:
    enabled: true
    defaultDashboardsEnabled: true
    sidecar:
      dashboards:
        enabled: true
        searchNamespace: ALL
      datasources:
        enabled: true
        defaultDatasourceEnabled: true
        isDefaultDatasource: true
        name: Prometheus
        uid: prometheus
        alertmanager:
          enabled: false
    additionalDataSources:
      - name: Loki
        uid: loki
        type: loki
        access: proxy
        url: http://{{ .Release.Name }}-loki-gateway
        editable: true
        jsonData:
          maxLines: 1000
    service:
      type: ClusterIP
      port: 80
      targetPort: 3000

loki:
  deploymentMode: SingleBinary
  loki:
    auth_enabled: false
    commonConfig:
      replication_factor: 1
    schemaConfig:
      configs:
        - from: "2024-04-01"
          store: tsdb
          object_store: filesystem
          schema: v13
          index:
            prefix: index_
            period: 24h
    storage:
      type: filesystem
  singleBinary:
    replicas: 1
    persistence:
      enabled: true
      size: 10Gi
  read:
    replicas: 0
  write:
    replicas: 0
  backend:
    replicas: 0
  chunksCache:
    enabled: false
  resultsCache:
    enabled: false
  lokiCanary:
    enabled: false
  test:
    enabled: false

promtail:
  config:
    clients:
      - url: http://{{ .Release.Name }}-loki-gateway/loki/api/v1/push
  serviceMonitor:
    enabled: true

dashboard:
  enabled: true

grafanaTargetGroupBinding:
  enabled: false
  targetGroupArn: ""
  targetType: ip
  serviceName: ""
  servicePort: 80
