replicaCount: 2

image:
  repository: ""
  tag: ""
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  httpsPort: null
  annotations: {}

targetGroupBinding:
  enabled: false
  targetGroupArn: ""
  targetType: ip

containerPort: 3000
